name: travel_gallery_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  flutter_signin_button: ^2.0.0

  cupertino_icons: ^1.0.2

  http: ^0.13.5
  cached_network_image: ^3.2.3

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true

  assets:
    - assets/images/

 
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-SemiBold.ttf
     - family: Rowdies
       fonts:
         - asset:  assets/fonts/Rowdies-Regular.ttf
 

